---
# Resumé de mes taches pour deployer l'appli
- name: create project directory
  file:
    path: "{{home}}/mini_projet"
    state: directory

- name: copy devops private key file
  copy:
    content: "{{ github_private_key }}"
    dest: "{{home}}/.ssh/id_rsa"
    owner: centos

- name: load the source code in github
  git:
    repo: "{{ repo_fake_backend  }}"
    dest: "{{home}}/mini_projet"
    accept_hostkey: yes
    force: yes
    recursive: no
    key_file: "{{ home }}/.ssh/id_rsa"
    version: "{{ fake_backend_source_branch }}"

- name: Log into DockerHub
  docker_login:
    username: "{{ dockerhub_login }}"
    password: "{{ dockerhub_password }}"

- name: Build an image and push it to a private repo/Docker hub
  docker_image:
    build:
      path: "{{home}}/mini_projet/fake-backend/"
    name: "{{ dockerhub_login }}/fake-backend"
    tag: "{{ tag_fake_backend }}"
    push: yes
    source: build

- name: container battlegame
  docker_container:
    name: battlegame
    image: "{{ dockerhub_login }}/fake-backend:{{ tag_fake_backend }}"
    state: started
   
    ports:
      - "8181:3000"
    env:
      DATABASE_HOST: "dbgame"
      DATABASE_PORT: "3306"
      DATABASE_USER: "battleuser"
      DATABASE_PASSWORD: "battlepass"
      DATABASE_NAME: "battleboat"

    volumes:
      - "{{ home }}/mini_projet/battleboat:/etc/backend/static"
    networks:
      - name: network_game    

